#!/bin/sh
echo "installing git"

#Installing all apt packages in one go
sudo apt-get update && clear
sudo apt-get install git && clear
sudo apt-get install sed && clear
sudo apt-get install curl && clear
sudo apt-get install -y dotnet-sdk-10.0 && clear
sudo apt-get install -y aspnetcore-runtime-10.0 && clear
sudo apt-get install -y dotnet-runtime-10.0 && clear
sudo apt-get install tor && clear
sudo apt-get install proxychains && clear
sudo apt-get install cabextract && clear
sudo apt-get install pipewire && clear

#installing XONE - for xbox Hardware
git clone https://github.com/medusalix/xone 
cd xone
sudo ./install.sh --release 
sudo xone-get-firmware.sh --skip-disclaimer && clear

#installing the LofreeScript - only fore my keyboard lofree flow lite
echo "options hid_apple fnmode=2" | sudo tee /etc/modprobe.d/20_lofree_fn_mode_fix.conf

echo "installing Vs code, Anytype, Brave, signal and DotNet"
mkdir $HOME/SetUpDownloads

wget -P $HOME/SetUpDownloads "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64" && clear
wget -P $HOME/SetUpDownloads "https://anytype-release.fra1.cdn.digitaloceanspaces.com/anytype_0.54.11_amd64.deb" && clear
curl -fsS https://dl.brave.com/install.sh | sh && clear


wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg && clear
cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null && clear

wget -O signal-desktop.sources https://updates.signal.org/static/desktop/apt/signal-desktop.sources && clear
cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null && clear

sudo apt update && sudo apt install signal-desktop && clear

wget https://packages.microsoft.com/config/debian/13/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && clear
sudo dpkg -i packages-microsoft-prod.deb && clear
rm packages-microsoft-prod.deb && clear


cd $HOME/SetUpDownloads
sudo dpkg -i * && clear

cd $HOME && rm -rf SetUpDownloads





echo "${green}creating scripts dir in $HOME"
cd $HOME && mkdir scripts

echo "${green}creating update script.."
touch $HOME/scripts/update

cat > $HOME/update <<- EOM
#!/bin/sh

echo "==> apt update..."
sudo apt update 2>&1
echo "==> apt update finished."

echo "==> Running full-upgrade..."
sudo apt full-upgrade -y 2>&1
echo "==> Finished full-upgrade"

echo "==>$ Cleaning..."
sudo apt autoclean -y 2>&1
sudo apt autoremove -y 2>&1
echo "==> All Updates & Cleanups Finished"

# Check if refind is installed
if dpkg -l refind >/dev/null 2>&1; then
sudo refind-install 2>&1
sudo refind-mkdefault 2>&1
fi 
EOM

echo "${green}created update scrip at: ${reset}$HOME/test/"
echo "\n\n"
clear




touch $HOME/.local/share/konsole/zsh.profile
cat > "$HOME/.local/share/konsole/zsh.profile" <<- 'EOM'
[Appearance]
ColorScheme=Linux

[General]
Command=/bin/zsh
Icon=utilities-terminal-symbolic
Name=zsh
Parent=FALLBACK/

EOM

kwriteconfig5 --file konsolerc --group "Desktop Entry" --key DefaultProfile "zsh.profile" 

# Install zsh
sudo apt install zsh -y

# Show version
zsh --version

# Set zsh as default shell
chsh -s /usr/bin/zsh 
clear

# Echo zsh. 
echo $SHELL

# Logout & Login if don't see zsh as default shell.
echo "Logout & Login if don't see zsh as default shell."

# Install oh-my-zsh. https://github.com/ohmyzsh/ohmyzsh
# Assuming you have curl installed.
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Use agnoster theme
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#agnoster
# Edit ZSH_THEME
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc

# Install powerline font
sudo apt-get install fonts-powerline -y
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf" && clear
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf" && clear
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf" && clear
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf" && clear

# Install powerlevel10k
sudo rm -R ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Edit zshrc and add powerlevelwget -P $HOME/SetUpDownloads "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

sed -i 's/ZSH_THEME="agnoster"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc

# Install plugins (zsh-autosuggestions and zsh-syntax-highlighting)
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete


# Enable plugins
sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-autocomplete)/g' ~/.zshrc

echo "Successfully Installed. Start new terminal and configure powerlevel10k."
echo "If p10k configuration wizard does not start automatically, run following"
echo "p10k configure"

printf '%s\n' 'export PATH="$PATH:$HOME/scripts"' >> "$HOME/.zshrc"
echo "konsoleprofile colors=Linux" >> .zshrc
zsh
clear
echo DONE!!!!!



