#!/bin/sh


green=$(tput setaf 2)
yellow=$(tput setaf 3)
reset=$(tput sgr0)
echo "${green}installing git"
sudo apt install git
sudo apt install sed

echo "installing Vs code, Anytype, Brave, signal and DotNet"
mkdir $HOME/SetUpDownloads
wget -P $HOME/SetUpDownloads "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"
wget -P $HOME/SetUpDownloads "https://anytype-release.fra1.cdn.digitaloceanspaces.com/anytype_0.54.11_amd64.deb"
curl -fsS https://dl.brave.com/install.sh | sh

# 1. Install our official public software signing key:
wget -O- https://updates.signal.org/desktop/apt/keys.asc | gpg --dearmor > signal-desktop-keyring.gpg
cat signal-desktop-keyring.gpg | sudo tee /usr/share/keyrings/signal-desktop-keyring.gpg > /dev/null

# 2. Add our repository to your list of repositories:
wget -O signal-desktop.sources https://updates.signal.org/static/desktop/apt/signal-desktop.sources
cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null

# 3. Update your package database and install Signal:
sudo apt update && sudo apt install signal-desktop

wget https://packages.microsoft.com/config/debian/13/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
rm packages-microsoft-prod.deb

sudo apt-get update && \
sudo apt-get install -y dotnet-sdk-10.0

sudo apt-get update && \
printf '%s\n' 'export PATH="$PATH:$HOME/scripts"' >> "$HOME/.zshrc"
echo -e "konsoleprofile colors=Linux" >> .zshrc

sudo apt-get install -y aspnetcore-runtime-10.0

sudo apt-get install -y dotnet-runtime-10.0


sudo apt install tor
sudo apt install proxychains


cd $HOME/SetUpDownloads
sudo dpkg -i *
cd $HOME && rm -rf SetUpDownloads





echo "${green}creating scripts dir in $HOME"
cd $HOME && mkdir scripts

echo "${green}creating update script.."
touch $HOME/scripts/update

cat > $HOME/update <<- EOM
#!/bin/sh

echo "==> apt update..."
sudo apt update 2>&1
echo "==> apt update finished."

echo "==> Running full-upgrade..."
sudo apt full-upgrade -y 2>&1
echo "==> Finished full-upgrade"

echo "==>$ Cleaning..."
sudo apt autoclean -y 2>&1
sudo apt autoremove -y 2>&1
echo "==> All Updates & Cleanups Finished"

# Check if refind is installed
if dpkg -l refind >/dev/null 2>&1; then
sudo refind-install 2>&1
sudo refind-mkdefault 2>&1
fi 
EOM

echo "${green}created update scrip at: ${reset}$HOME/test/"
echo "\n\n"


wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
wget -P $HOME/.local/share/fonts "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
cd

echo "${green}installing curl \n"
sudo apt install curl





touch $HOME/.local/share/konsole/zsh.profile
cat > "$HOME/.local/share/konsole/zsh.profile" <<- 'EOM'
[Appearance]
ColorScheme=Linux

[General]
Command=/bin/zsh
Icon=utilities-terminal-symbolic
Name=zsh
Parent=FALLBACK/

EOM

kwriteconfig5 --file konsolerc --group "Desktop Entry" --key DefaultProfile "zsh.profile" 






# Install zsh
sudo apt install zsh -y

# Show version
zsh --version

# Set zsh as default shell
chsh -s /usr/bin/zsh 


# Echo zsh. 
echo $SHELL

# Logout & Login if don't see zsh as default shell.
echo "Logout & Login if don't see zsh as default shell."

# Install oh-my-zsh. https://github.com/ohmyzsh/ohmyzsh
# Assuming you have curl installed.
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Use agnoster theme
# https://github.com/ohmyzsh/ohmyzsh/wiki/Themes#agnoster
# Edit ZSH_THEME
sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="agnoster"/g' ~/.zshrc

# Install powerline font
sudo apt-get install fonts-powerline -y

# Install powerlevel10k
sudo rm -R ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# Edit zshrc and add powerlevelwget -P $HOME/SetUpDownloads "https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64"

sed -i 's/ZSH_THEME="agnoster"/ZSH_THEME="powerlevel10k\/powerlevel10k"/g' ~/.zshrc

# Install plugins (zsh-autosuggestions and zsh-syntax-highlighting)
echo "${green}Installing Plugins\n"
git clone https://github.com/zsh-users/zsh-autosuggestions.git $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git $ZSH_CUSTOM/plugins/zsh-autocomplete


# Enable plugins
sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions zsh-autocomplete)/g' ~/.zshrc

echo "Successfully Installed. Start new terminal and configure powerlevel10k."
echo "If p10k configuration wizard does not start automatically, run following"
echo "p10k configure"

printf '%s\n' 'export PATH="$PATH:$HOME/scripts"' >> "$HOME/.zshrc"
echo "konsoleprofile colors=Linux" >> .zshrc
zsh
clear

update
echo DONE!!!!!



